---
commitizen:
  name: cz_conventional_commits
  tag_format: aws_backend-${version}
  update_changelog_on_bump: true
  version: 0.1.0
  changelog_file: aws/backend/CHANGELOG.md
  changelog_incremental: true
