---
commitizen:
  name: cz_conventional_commits
  tag_format: aws_cloudfront_waf-${version}
  update_changelog_on_bump: true
  version: 0.1.0
  changelog_file: aws/cloudfront_waf/CHANGELOG.md
  changelog_incremental: true
