---
commitizen:
  name: cz_conventional_commits
  tag_format: aws_logging-${version}
  update_changelog_on_bump: true
  version: 0.1.0
  changelog_file: aws/logging/CHANGELOG.md
  changelog_incremental: true
