---
commitizen:
  name: cz_conventional_commits
  tag_format: aws_fargate_service-${version}
  update_changelog_on_bump: true
  version: 0.1.0
  changelog_file: aws/fargate_service/CHANGELOG.md
  changelog_incremental: true
