---
commitizen:
  name: cz_conventional_commits
  tag_format: aws_serverless_database-${version}
  update_changelog_on_bump: true
  version: 0.1.0
  changelog_file: aws/serverless_database/CHANGELOG.md
  changelog_incremental: true
