#!/usr/bin/env bash

ROOT_PATH="$(dirname "$0")/.."
MODULE_PATH="$1"

# Determine if a command exists on the current system.
command_exists()  {
  command -v "$1" >/dev/null 2>&1
}

# Attempt to install the jq package.
install_jq() {
  echo 'Attempting to install jq...'

  if command_exists brew; then
    brew install jq
  elif command_exists apt-get; then
    sudo apt-get install -y jq
  elif command_exists dnf; then
    sudo dnf install -y jq
  elif command_exists yum; then
    sudo yum install -y jq
  else
    echo 'error: unable to determine package manager'
    exit 1
  fi
}

# Verify that jq is available on the system.
if ! command_exists jq
then
  install_jq
fi

# Combine the package.json files.
jq -s ".[0] * .[1] | .repository.directory=\"${MODULE_PATH}\"" \
  "${ROOT_PATH}/package.base.json" \
  "${ROOT_PATH}/${MODULE_PATH}/package.module.json" \
  > "${ROOT_PATH}/${MODULE_PATH}/package.json"

module_name=$(jq -r '.name' "${ROOT_PATH}/${MODULE_PATH}/package.json")

echo 'Installing dependencies...'
cp LICENSE "${MODULE_PATH}/."
cd "${MODULE_PATH}"
npm install

echo "Releasing module ${module_name}..."
npx semantic-release -t "${module_name}/\${version}"

echo 'Cleaning up...'
#rm -rf package.json package-lock.json LICENSE node_modules
