name: Release module
on:
  pull_request:
  workflow_dispatch:
    inputs:
      module_path:
        description: 'Path to the module to be released'
        required: true
        type: string


#permissions:
#  issues: write
#  contents: write
#  pull-requests: write

jobs:
  release-module:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/release ${{ github.event.inputs.module_path }}
